export const CONTENT = {
  ACTIONS_HEADING: "События",
  BUTTON_ENS_TEXT: "Пополнить ЕНС",
  ENS_TEXT_DETAILS: "Анализ ЕНС доступен на платном тарифе",
  TEXT_AMOUNT_ALREADY_PAID: "Оплачено:",
  BUTTON_TO_PAY: "Оплатить",
  BUTTON_PAID: "Уже оплачено",
  BUTTON_PASSED: "Уже сдано",
  BUTTON_FORM: "Сформировать",
  TITLE_FORMED: "Сформировано ",
  BUTTON_UPDATE: "Обновить",
  BUTTON_UPDATE_ACTIONS: "Обновить расчет",
  UPDATE_DATA_HEADING: "Обновите данные",
  TEXT_AMOUNT_TO_PAY: "К уплате:",
  OVERDUE_WARNING: "просрочено",
  TAXES_QUARTER_TEXT: "Налог за",
  TAXES_TAXBASE_TEXT: "Налоговая база за",
  TAXES_QUARTER_END: " кв ",
  TEXT_DECLARATION: "Перед формированием проверьте раздел",
  TEXT_DETAILS: "Подробнее →",
  UPDATE_TAXES_LINK: "Налоговая база",
  NOTIFCATION_REPORT_ERROR: "Ошибка формирования файлов. Попробуйте еще раз",
  NOTIFCATION_DOWNLOAD_ERROR: "Ошибка скачивания файла. Попробуйте еще раз",
  NOTIFCATION_TASKS_ERROR: "Ошибка получения событий. Попробуйте позже",
  DECLARATION_TOOLTIP:
    "Необходимо добавить выписки по всем имеющимся счетам, прописать комиссию и внести данные по наличной выручке (если есть)",
  NOTIFICATION_DOWNLOAD_SUCCESS: "Скачивание файла",
  UPDATE_DATA_TEXT:
    "Закончился I квартал 2024 года, для корректного расчета добавьте все источники данных в разделе",
  TITLE_NEW_ACTIONS: "Сервис Бухгалтерия успешно подключен",
  DESCRIPTION_NEW_ACTIONS_ONE:
    "Формируем налоговые задачи, это может занять до 10 минут",
  DESCRIPTION_NEW_ACTIONS_TWO:
    "Для корректного расчета необходимо подгрузить выписки в разделе",
  OPERATIONS_LINK: "Операции →",
  SOON_WARNING: "скоро",
  TOOLTIP_USN_TEXT_ONE: "Из них:",
  TOOLTIP_USN_TEXT_TWO: " - срок уплаты до",
  TOOLTIP_USN_TEXT_THREE: " - задолженность за предыдущие периоды",
  TOOLTIP_REPORT_TEXT_ONE: "Сумма в сформированном Уведомлении: ",
  TOOLTIP_REPORT_TEXT_TWO: "Сумма налога в текущем расчете: ",
  TOOLTIP_REPORT_TEXT_THREE:
    "Для формирования Уведомления с\u00A0актуальными данными нажмите кнопку Обновить",
  NOTIFICATIONS_TITLE: "Уведомления",
  TIMER_START: "Через ",
  TIMER_SEC: " сек.",
  BUTTON_IN_UDPATING: "Обновляется",
  TAXES_ERROR_HEADING: "Что-то пошло не так",
  TAXES_ERROR_DESCRIPTION: "Мы знаем о проблеме и решаем её",
}

export const LINK_MAP: Record<string, string> = {
  "/taxes": "Операции →",
  "/settings": "Настройки →",
}
